# Generated by Django 5.2.15 on 2026-06-09 09:23
# Migrazione iniziale: crea le tabelle principali del noleggio.

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, verbose_name='descrizione')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('description', models.TextField(verbose_name='descrizione')),
                ('total_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantità totale')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='prezzo giornaliero')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='immagine')),
                ('is_active', models.BooleanField(default=True, verbose_name='disponibile nel catalogo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creata il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificata il')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='rentals.equipmentcategory', verbose_name='tipologia')),
            ],
            options={
                'verbose_name': 'attrezzatura',
                'verbose_name_plural': 'attrezzature',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='data di inizio')),
                ('end_date', models.DateField(verbose_name='data di fine')),
                ('status', models.CharField(choices=[('confirmed', 'Confermata'), ('cancelled', 'Cancellata')], default='confirmed', max_length=20, verbose_name='stato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creata il')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancellata il')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'prenotazione',
                'verbose_name_plural': 'prenotazioni',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantità')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='prezzo giornaliero applicato')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_items', to='rentals.equipment', verbose_name='attrezzatura')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rentals.reservation', verbose_name='prenotazione')),
            ],
            options={
                'verbose_name': 'riga prenotazione',
                'verbose_name_plural': 'righe prenotazione',
            },
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_equipment_name_per_category'),
        ),
        migrations.AddConstraint(
            model_name='reservationitem',
            constraint=models.UniqueConstraint(fields=('reservation', 'equipment'), name='unique_equipment_per_reservation'),
        ),
    ]
